### ISSUE TITLE
Incorrect value reported for storage device vendor

### ISSUE THREAD

**Issue by priteau** [grid5000/g5k-checks#6]
On some hardware, the output of g5k-checks reports an incorrect value for the vendor of a storage device. The wrong value is also present in Ohai.

For example, on Chameleon hardware (this is Ohai output, not Reference API data):

``` json
"sda": {
  "size": "488397168",
  "removable": "0",
  "model": "ST9250610NS",
  "rev": "AA63",
  "state": "running",
  "timeout": "90",
  "vendor": "ATA"
}
```

I checked a couple of Grid'5000 clusters, same problem (this is Reference API data). This is a random node on parapluie (some values removed):

``` json
{
  "device": "sda",
  "driver": "ahci",
  "interface": "SATA",
  "storage": "HDD",
  "vendor": "ATA"
}
```

parapide shows `"vendor": null`.

The version of Ohai doesn't matter, since the problem actually comes from the value exported by the Linux kernel itself:

```
$ cat /sys/block/sda/device/vendor
ATA
```

**Comment by priteau** [comment]
This is the code we use in our reference-generator to set the correct vendor value:

``` ruby
case lookup('chameleon_generated', node_uid, 'block_devices', dev, 'model')
when /^HUA/
  storage_vendors[dev] = 'Hitachi'
when /^INTEL/
  storage_vendors[dev] = 'Intel'
when /^ST.*/
  storage_vendors[dev] = 'Seagate'
when /^WD.*/
  storage_vendors[dev] = 'Western Digital'
else
  storage_vendors[dev] = 'Unknown'
end
```

**Comment by deadlybore** [comment]
I face a similar problem regarding the rev firmware.

For example on chinqchint-33 :

On the reference-api we have :

```
storage_devices"=>[{"device"=>"sda",
      "driver"=>"ahci",
      "interface"=>"SATA II",
      "model"=>"ST3250620NS",
      "rev"=>"3.AEK",
      "size"=>250059350016,
      "storage"=>"HDD",
      "vendor"=>nil}]
```

On the node :

```
root@chinqchint-33:~# hdparm -I /dev/sda

/dev/sda:

ATA device, with non-removable media
    Model Number:       ST3250620NS
    Serial Number:      9QE6YWTY
    Firmware Revision:  3.AEK
```

what ohai retrieve from the node :

```
{"size"=>"488397168", "removable"=>"0", "model"=>"ST3250620NS", "rev"=>"K", "state"=>"running", "timeout"=>"30", "vendor"=>"ATA"}
```

Moreover g5k-checks retrieve nothing from the api thus leading to an exception 
`cat /var/lib/oar/checklogs/OAR_Disk_should_have_the_correct_revision_sda`

```
{"started_at":"2016-03-30 14:49:27 +0200","exception":"K, 3.0, block_devices, sda, rev","status":"failed","finished_at":"2016-03-30 14:49:27 +0200","run_time":0.000228669}
```

**Comment by jgaida** [comment]
There is a similar issue with bios versions

On the G5K Ref API: 

```
chimint-1:
  bios:
    release_date: 10/22/2010
    vendor: Dell Inc.
    version: 1.5
```

With g5k-check:

```
chimint-1:
  bios:
    release_date: 10/22/2010
    vendor: Dell Inc.
    version: 1.5.3
```

**Comment by jgaida** [comment]
I fixed the BIOS version problem in 5dbd55ac

**Comment by jgaida** [comment]
For the 'rev' problem encountered by @deadlybore, ohai gets the info from /sys/block/sda/device/rev (see ohai/lib/ohai/plugins/linux/block_device.rb) and the data is actually truncated on this file.

**Comment by jgaida** [comment]
Concerning the initial problem reported by @priteau, it seems that `lshw` is capable of finding the hard-drive vendor:

```
$ sudo lshw -class disk -class storage -json
[...]
        "description" : "ATA Disk",
        "product" : "Hitachi HDT72502",
        "vendor" : "Hitachi",
        "physid" : "0.0.0",
        "businfo" : "scsi@0:0.0.0",
        "logicalname" : "/dev/sda",
        "dev" : "8:0",
        "version" : "A7EA",
        "serial" : "VFJ111R7C38UKU",
```

**Comment by jgaida** [comment]
I updated g5k-checks to use hdparm for the rev/version string and lshw for the vendor when available. It still falls back to /sys/block/sda/device/rev and /sys/block/sda/device/vendor when the values cannot be retrieves with those tools.

**Comment by nmichon** [comment]
The latest version (0.7.8) should contain all the fixes regarding disk vendor and firmware revision.
Closing this issue as it seems those values are now correctly managed.
